### ISSUE TITLE
Compress images on the landing page

### ISSUE THREAD

**Issue by emileber** [hackathon-comiko/comiko#44]
Right now, 18.7Mb of images really _slows_ down the page rendering. I think we can safely get that under 1Mb.

**Comment by adlf** [comment]
I'll take this.

**Comment by emileber** [comment]
@adlf First of all thanks, the landing page is in the _gh-pages_ branch.

**Comment by emileber** [comment]
Oh @adlf, it looks like someone took care of it already.

**Comment by emileber** [comment]
This is now merged, thanks everyone!

**Comment by emileber** [comment]
From 18.7Mb down to ~500Kb! 🍾
