### ISSUE TITLE
Add our logo to the README

### ISSUE THREAD

**Issue by kimond** [hackathon-comiko/comiko#50]
The file is in the `lib/assets/` directory.

**Comment by kimond** [comment]
@emileber I think this is an easy issue to flag as hacktoberfest.

**Comment by emileber** [comment]
Which one? `comiko.png` or `comiko_logo.png`?

**Comment by kimond** [comment]
I would say `comiko.png`. What do you think?

**Comment by emileber** [comment]
Yes, that's what's best. Let's also center it like [most](https://github.com/avajs/ava) [_sindresorhus_](https://github.com/sindresorhus) [repos](https://github.com/sindresorhus/xo) and add one of the mobile screenshots somewhere in the description (located in the `gh-pages` branch in the `assets/images` directory).
