### ISSUE TITLE
Add code coverage with badge

### ISSUE THREAD

**Issue by GabLeRoux** [hackathon-comiko/comiko#65]
🍷 I think this project could get some attention sooner or later so we should setup some tools to keep track of Quality

📜  We should use [codecov.io](https://codecov.io/gh). Here's [an example dart repository with codecov setup](https://github.com/codecov/dart)

ReadMe badge should look something like that

```markdown
[![codecov.io](http://codecov.io/github/comiko-app/comiko/coverage.svg?branch=master)](http://codecov.io/github/comiko-app/comiko?branch=master)
```

**Comment by kimond** [comment]
I did it with my project https://github.com/kimond/cmustify. I'm on it.

**Comment by kimond** [comment]
Unfortunately, we have a dependency issue with flutter and dart_codecov_generator.

```
ERR : Incompatible version constraints on logging:
    | - build 0.9.2 depends on version ^0.11.2
    | - csslib 0.14.1 depends on version >=0.9.0 <0.12.0
    | - dart_codecov_generator 0.4.0 depends on version >=0.9.0 <0.11.0
    | - flutter_test 0.0.14-dev depends on version 0.11.3+1
    | - kernel 0.3.0-alpha.1 depends on version ^0.11.2
```
We could try to contribute to the codecov dart plugin in order to match flutter dependencies.

I took a look at https://github.com/block-forest/dart-coveralls and we have the same dependency issue :disappointed:

**Comment by kimond** [comment]
After investigating on the issue, I managed to discover that the pub version was not up to date with the GitHub one.

It works using the following config
```
dart_codecov_generator:
    git: https://github.com/codecov/dart.git
```

**Comment by GabLeRoux** [comment]
@kimond you rock 🤘 good job!

**Comment by kimond** [comment]
@GabLeRoux better: with flutter we just need to type: `flutter test --coverage`. Here an example: https://github.com/goposse/fluro/blob/master/.travis.yml

**Comment by GabLeRoux** [comment]
My mind is blown 💥  I love it. Let’s coverage all the things! :D

**Comment by GabLeRoux** [comment]
https://codecov.io/gh/comiko-app/comiko/commit/1c3b24e04820dcb603e99fcf65b3a29706162123

Says there’s an error, did you fill env var?

CI log looks fine:
https://travis-ci.org/comiko-app/comiko/builds/285856580#L629

**Comment by kimond** [comment]
I think it is because our only test is a dummy test so there's no coverage at all.

**Comment by GabLeRoux** [comment]
Nice opportunity to make things better then. :rocket: I’ll try to write some dart tests soon :+1:
